### ISSUE TITLE
Webhook component panic's when creating a new snapshot

### ISSUE THREAD

**Issue by Jorijn** [kubernetes-csi/external-snapshotter#1003]
**What happened**:

My Velero backups started failing when I upgraded the project to v7.0.0.

**What you expected to happen**:

Velero can create snapshots of my PVCs.

**How to reproduce it**:

To be perfectly transparent, I don't fully understand how the snapshots are requested, and how the webhooks are handled/requested. 

**Anything else we need to know?**:

Logs:

```
2024/02/09 06:37:28 http: panic serving 10.244.2.235:41374: runtime error: invalid memory address or nil pointer dereference
goroutine 483 [running]:
net/http.(*conn).serve.func1()
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/net/http/server.go:1868 +0xb9
panic({0x1482be0?, 0x2337410?})
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/runtime/panic.go:920 +0x270
github.com/kubernetes-csi/external-snapshotter/v7/pkg/validation-webhook.checkSnapshotContentImmutableFieldsV1(0xc0007cc540, 0xc0007cc700)
	/workspace/pkg/validation-webhook/snapshot.go:250 +0x1fd
github.com/kubernetes-csi/external-snapshotter/v7/pkg/validation-webhook.decideSnapshotContentV1(0xc0008ad4d8?, 0xc0007d6000?, 0x1)
	/workspace/pkg/validation-webhook/snapshot.go:150 +0x86
github.com/kubernetes-csi/external-snapshotter/v7/pkg/validation-webhook.admitter.Admit({{0x186fc38?, 0xc000438b00?}}, {{{0xc000891580, 0xf}, {0xc0001fd110, 0x13}}, 0xc000603a00, 0x0})
	/workspace/pkg/validation-webhook/snapshot.go:98 +0x93e
github.com/kubernetes-csi/external-snapshotter/v7/pkg/validation-webhook.serve({0x1877d80, 0xc0002448c0}, 0xc000458900, {{0x1869a00?, 0xc000636be0?}})
	/workspace/pkg/validation-webhook/webhook.go:167 +0xe8c
github.com/kubernetes-csi/external-snapshotter/v7/pkg/validation-webhook.serveSnapshotWebhook.ServeHTTP(...)
	/workspace/pkg/validation-webhook/webhook.go:195
net/http.(*ServeMux).ServeHTTP(0x4105a5?, {0x1877d80, 0xc0002448c0}, 0xc000458900)
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0x186fd00?}, {0x1877d80?, 0xc0002448c0?}, 0x6?)
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004de090, {0x1880fa0, 0xc000702ea0})
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/go/pkg/csiprow.XXXXKHnLNP/go-1.21.5/src/net/http/server.go:3086 +0x5cb
```

**Environment**:
- Driver version: v7.0.0
- Kubernetes version (use `kubectl version`): Server Version: v1.29.1
- OS (e.g. from /etc/os-release): Talos Linux v1.6.4
- Kernel (e.g. `uname -a`): Linux (6.1.74-talos)
- Install tools: Installed using the Helm chart https://github.com/piraeusdatastore/helm-charts

**Comment by xing-yang** [comment]
Is the validation webhook deployed before the upgrade?  Can you provide the full logs from the validation webhook, csi snapshotter and snapshot-controller?  Can you also provide Velero logs?  Which CSI driver is this?

**Comment by xing-yang** [comment]
I suspect it is because oldSnapcontent.Spec.SourceVolumeMode is nil:
https://github.com/kubernetes-csi/external-snapshotter/blob/v7.0.0/pkg/validation-webhook/snapshot.go#L250

Have you updated the VolumeSnapshot CRDs to the latest?

**Comment by xing-yang** [comment]
> Thanks for the quick fix. Do you still need additional information from me, now that the issue is fixed and closed?

@Jorijn, v7.0.1 is released: https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v7.0.1
Can you verify if the bug is fixed?

**Comment by Jorijn** [comment]
Yes. The bug is fixed. Thanks again!
